on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull main
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: connect, pull and reload nginx
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            cd ${{ secrets.WORK_DIR }}toollab &&
            git fetch --all &&
            git checkout ${{ secrets.MAIN_BRANCH_TOOLLAB }} &&
            git reset --hard origin/${{ secrets.MAIN_BRANCH_TOOLLAB }} &&
            sudo systemctl reload nginx
          '

      - name: cleanup
        run: rm -rf ~/.ssh
